# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0004_usuario_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='telephone',
        ),
    ]
