# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jornal', '0005_remove_usuario_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='funcao',
            field=models.CharField(blank=True, choices=[('fo', 'Fotógrafo'), ('jo', 'Jornalista')], default='jo', max_length=2, null=True),
        ),
    ]
